services:

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - namenode_data:/hadoop/dfs/name

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - datanode_data:/hadoop/dfs/data
    ports:
      - "9864:9864"
    depends_on:
      - namenode

  spark-master:
    image: apache/spark:3.5.1
    container_name: spark-master
    entrypoint: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "8080:8080"
      - "7077:7077"

  spark-worker:
    image: apache/spark:3.5.1
    container_name: spark-worker
    entrypoint: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    environment:
      - SPARK_NO_DAEMONIZE=true
    depends_on:
      - spark-master

  jupyter:
    image: quay.io/jupyter/pyspark-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/work
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark-master

volumes:
  namenode_data:
  datanode_data:
